import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class Productservice {
  productList = [
    {
      "id": 1,
      "title": "Blue Floral Lace Lingerie Set",
      "price": 240.99,
      "description": "Delicate blue floral lace bra and panty set with soft underwire support and intricate floral embroidery. Perfect for a romantic evening or everyday luxury.",
      "category": "lingerie",
      "image": "/bluefloral.jpeg",
    },
    {
      "id": 2,
      "title": "Pink Sheer Lingerie Piece",
      "price": 290.99,
      "description": "Elegant pink sheer one-piece lingerie with lace trim detailing. Features adjustable straps and a flattering silhouette for all body types.",
      "category": "lingerie",
      "image": "/pinklingeriepiece.jpeg",
    },
    {
      "id": 3,
      "title": "Floral Black Lace Lingerie Set",
      "price": 340.99,
      "description": "Sophisticated black floral lace two-piece set with a balconette bra and matching high-waist brief. Timeless design with a modern twist.",
      "category": "lingerie",
      "image": "/floralblack.jpeg",
    },
    {
      "id": 4,
      "title": "Red Strappy Lingerie Set",
      "price": 390.99,
      "description": "Bold red strappy lingerie set with intricate cage-style detailing. This daring design features adjustable straps and a plunge neckline for a seductive look.",
      "category": "lingerie",
      "image": "/rednumber.jpeg",
    },
    {
      "id": 5,
      "title": "Leopard Print Lingerie Thong Set",
      "price": 220.99,
      "description": "Wild and alluring leopard print bra and thong set. Soft microfiber fabric with animal print pattern, underwire bra with adjustable straps.",
      "category": "lingerie",
      "image": "/leopardlingerie.jpeg",
    },
    {
      "id": 6,
      "title": "Green Sexy Strappy Lingerie Set",
      "price": 360.99,
      "description": "Striking emerald green strappy lingerie set featuring a wrap-style bra and matching thong. The bold color and sleek design make it an eye-catching choice.",
      "category": "lingerie",
      "image": "/Greensexylingerie.webp",
    },
    {
      "id": 7,
      "title": "Blue Lace Lingerie Piece",
      "price": 270.99,
      "description": "Beautiful royal blue lace one-piece babydoll lingerie with scalloped hem and spaghetti straps. Features a flowy silhouette with a matching thong.",
      "category": "lingerie",
      "image": "/Bluelingeriepiece.jpeg",
    },
    {
      "id": 8,
      "title": "Black Silk Satin Lingerie Set",
      "price": 440.99,
      "description": "Luxurious black silk satin slip dress and robe set. Ultra-soft satin fabric drapes elegantly over the body with lace trim accents for a touch of romance.",
      "category": "lingerie",
      "image": "/Blacksilkset.webp",
    },
    {
      "id": 9,
      "title": "Four-Pack Thong Set",
      "price": 180.99,
      "description": "Value pack of four colorful thongs in assorted colors. Made from soft stretch fabric with a comfortable waistband. Perfect for everyday wear or gifting.",
      "category": "panties",
      "image": "/fourthongs.jpeg",
    },
    {
      "id": 10,
      "title": "Red Lace G-String",
      "price": 90.99,
      "description": "Seductive red lace G-string with delicate floral lace fabric and thin elastic waistband. Barely-there design for seamless wear under any outfit.",
      "category": "panties",
      "image": "/redgstring.jpeg",
    },
    {
      "id": 11,
      "title": "Two-Piece Lace Panty Set",
      "price": 140.99,
      "description": "Set of two elegant lace panties in complementary neutral tones. Features a low-rise cut with scalloped lace trim and soft elastic waistband.",
      "category": "panties",
      "image": "/twolacepanties.jpeg",
    },
    {
      "id": 12,
      "title": "Five-Pack Mixed Panty Set",
      "price": 240.99,
      "description": "Versatile five-pack of mixed-style panties including bikinis, briefs, and thongs in a variety of colors and fabrics. Great value for everyday essentials.",
      "category": "panties",
      "image": "/fivepanties.jpeg",
    },
    {
      "id": 13,
      "title": "Three Pearl Embellished Panty Set",
      "price": 190.99,
      "description": "Glamorous set of three panties with delicate pearl bead embellishments. Features sheer mesh fabric with strategic pearl detailing for a luxurious feel.",
      "category": "panties",
      "image": "/threepearls.jpeg",
    },
    {
      "id": 14,
      "title": "Seven-Pack Seamless Panty Set",
      "price": 290.99,
      "description": "Ultimate everyday essentials: a seven-pack of seamless panties in neutral and earth tones. No-show design with laser-cut edges, perfect under fitted clothing.",
      "category": "panties",
      "image": "/sevenseamless.jpeg",
    },
    {
      "id": 15,
      "title": "Black & White Lace Bra Set",
      "price": 320.99,
      "description": "Classic black and white contrast lace bra with underwire support and fully adjustable straps. Features a plunge neckline with matching lace details.",
      "category": "bras",
      "image": "/blackwhitebra.jpeg",
    },
    {
      "id": 16,
      "title": "Seamless Multicolor Bra Set",
      "price": 380.99,
      "description": "Pack of four seamless wireless bras in soft neutral tones including nude, blush, taupe, and sage. Ultra-comfortable with a smooth finish and light padding.",
      "category": "bras",
      "image": "/seamlessbraset.jpeg",
    },
    {
      "id": 17,
      "title": "Black Cross-Back Sports Bra",
      "price": 260.99,
      "description": "Stylish black cross-back bra with medium support and removable padding. The strappy cross design doubles as a fashion statement, suitable for workouts or casual wear.",
      "category": "bras",
      "image": "/blackcrossbra.webp",
    },
    {
      "id": 18,
      "title": "Pink Floral Lace Bra",
      "price": 280.99,
      "description": "Feminine pink floral lace underwire bra with a balconette design. Intricate lace overlay with satin bow detail at center front and cushioned underwire.",
      "category": "bras",
      "image": "/pinkbra.webp",
    },
    {
      "id": 19,
      "title": "Five-Pack Wireless T-Shirt Bras",
      "price": 440.99,
      "description": "Essential five-pack of wireless t-shirt bras in nude, black, white, grey, and blush. Lightly padded cups with a smooth moulded finish — invisible under any top.",
      "category": "bras",
      "image": "/fivepiece.jpeg",
    },
    {
      "id": 20,
      "title": "White Nightwear Robe & Bra Set",
      "price": 490.99,
      "description": "Elegant white satin nightwear set including a kimono-style robe, bralette, and shorts. Soft satin fabric with lace trim accents — ideal for honeymoons or special occasions.",
      "category": "lingerie",
     "image": "/whiteNightwear.webp",
    }
  ]

  getProducts(){
    return this.productList;
   }
}
